server:
  port: 9921

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9901/eureka/

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangpeijian/service-config-repertory.git
          searchPaths: /