server:
  port: 9921

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.76.51.38:9901/eureka/

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangpeijian/service-config-repertory.git
          searchPaths: /
          username:
          password:
      label: master
